esphome:
  name: chinchilla_scale
  friendly_name: Chinchilla Scale

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.178.124
    gateway: 192.168.178.1
    subnet: 255.255.255.0

globals:
#-------------------------------------------------------------------------
# initial_zero must be adjusted for calibration  and match the value below
#--------------------------------------------------------------------------
  - id: initial_zero
    type: float
    restore_value: yes
    initial_value: '-153238'
    
  - id: auto_tare_enabled
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: auto_tare_difference
    type: float
    restore_value: yes
    initial_value: '0'

  - id: scale_state
    type: int
    restore_value: no
    initial_value: '0'

  - id: stable_count
    type: int
    restore_value: no
    initial_value: '0'

  - id: measurement_sum
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: measurement_count
    type: int
    restore_value: no
    initial_value: '0'

  - id: measurement_start_value
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: last_stable_reading
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: zero_stable_count
    type: int
    restore_value: no
    initial_value: '0'

  - id: zero_sum
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: zero_count
    type: int
    restore_value: no
    initial_value: '0'

  - id: zero_last_stable_reading
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: last_stable_zero
    type: float
    restore_value: no
    initial_value: '0.0'

button:
  - platform: template
    id: smart_scale_manual_tare_action_switch
    name: "Tare"
    icon: mdi:scale-balance
    on_press:
      - lambda: |-
          id(auto_tare_difference) = id(initial_zero) - id(smart_scale_hx711_value_raw).state;
      - sensor.template.publish:
          id: smart_scale_hx711_value_raw_diagnostic
          state: !lambda 'return id(smart_scale_hx711_value_raw).state;'

switch:
  - platform: template
    id: smart_scale_continuous_tare_enabled
    name: "Auto Tare"
    icon: "mdi:scale-unbalanced"
    entity_category: "config"
    lambda: |-
      return id(auto_tare_enabled);
    turn_on_action:
      - lambda: |-
          id(auto_tare_enabled) = true;
    turn_off_action:
      - lambda: |-
          id(auto_tare_enabled) = false;

sensor:
  - platform: template
    id: smart_scale_initial_zero
    name: "Initial Zero Value"
    lambda: |-
      return id(initial_zero);
    update_interval: 1s
    
  - platform: template
    id: smart_scale_auto_tare_difference
    name: "Auto Tare Offset"
    lambda: |-
      return id(auto_tare_difference);
    update_interval: 1s

  - platform: template
    id: smart_scale_auto_tare_deviance
    entity_category: "diagnostic"
    name: "Calibration Difference"
    lambda: |-
      return (int(
        (id(smart_scale_hx711_value_raw).state 
         - (id(initial_zero) - id(auto_tare_difference))) 
        / 100)) * 100;
    update_interval: 1s
    
  - platform: homeassistant
    id: homeassistant_initial_zero
    entity_id: input_number.smart_scale_initial_zero
    on_value:
      then:
        - lambda: |-
            id(initial_zero) = x;
  
  - platform: hx711
    id: smart_scale_hx711_value_raw
    internal: true
    dout_pin: 3
    clk_pin: 4
    gain: 128
    update_interval: 0.2s
    filters:
      - quantile:
          window_size: 10
          send_every: 1
          send_first_at: 1
          quantile: 0.9
    on_value:
      then:
        - sensor.template.publish:
            id: smart_scale_hx711_value
            state: !lambda 'return id(smart_scale_hx711_value_raw).state;'

  - platform: template
    id: smart_scale_hx711_value_raw_diagnostic
    name: "HX711 Raw Data"
    entity_category: "diagnostic"

  - platform: template
    id: smart_scale_hx711_value
    name: "Weight (current)"
    icon: "mdi:weight"
    internal: false
    filters:
      - lambda: 'return x + id(auto_tare_difference);'
# -------------------------------------------------------------
# CALIBRATION 
# -------------------------------------------------------------
      - calibrate_linear:
          - -153238 -> 0
          - -469545 -> 1395
      - lambda: |-
          if (x > -0.1 && x < 0.1) {
            return 0.0;
          } else {
            return x;
          }
    unit_of_measurement: "g"
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    name: "Last Measurement"
    id: smart_scale_final_measurement
    icon: "mdi:weight"
    unit_of_measurement: "g"
    accuracy_decimals: 2
    update_interval: never

